services:
  api:
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    ports:
      - "8080:8080"
    # TODO: wait for mysql to start.
    # to be added when creating the db layer in application code.
    volumes:
      - ".:/app"

  mysql:
    image: "mysql:8.4"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-sample_todo_app}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
  mysql: {}
