services:
  api:
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
    depends_on:
      mysql:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"

  mysql:
    image: "mysql:8.4"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-sample_todo_app}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: "5s"
      retries: 10
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
  mysql: {}
